/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Game, Move } from "./libs/draughts";
export namespace Components {
    interface AppBoard {
        "gamestate": Game;
    }
    interface AppGameLocal {
    }
    interface AppGameOnline {
        "name": string;
    }
    interface AppHome {
    }
    interface AppPiece {
    }
    interface AppResults {
        "winner": number;
    }
    interface AppRoot {
    }
}
declare global {
    interface HTMLAppBoardElement extends Components.AppBoard, HTMLStencilElement {
    }
    var HTMLAppBoardElement: {
        prototype: HTMLAppBoardElement;
        new (): HTMLAppBoardElement;
    };
    interface HTMLAppGameLocalElement extends Components.AppGameLocal, HTMLStencilElement {
    }
    var HTMLAppGameLocalElement: {
        prototype: HTMLAppGameLocalElement;
        new (): HTMLAppGameLocalElement;
    };
    interface HTMLAppGameOnlineElement extends Components.AppGameOnline, HTMLStencilElement {
    }
    var HTMLAppGameOnlineElement: {
        prototype: HTMLAppGameOnlineElement;
        new (): HTMLAppGameOnlineElement;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppPieceElement extends Components.AppPiece, HTMLStencilElement {
    }
    var HTMLAppPieceElement: {
        prototype: HTMLAppPieceElement;
        new (): HTMLAppPieceElement;
    };
    interface HTMLAppResultsElement extends Components.AppResults, HTMLStencilElement {
    }
    var HTMLAppResultsElement: {
        prototype: HTMLAppResultsElement;
        new (): HTMLAppResultsElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLElementTagNameMap {
        "app-board": HTMLAppBoardElement;
        "app-game-local": HTMLAppGameLocalElement;
        "app-game-online": HTMLAppGameOnlineElement;
        "app-home": HTMLAppHomeElement;
        "app-piece": HTMLAppPieceElement;
        "app-results": HTMLAppResultsElement;
        "app-root": HTMLAppRootElement;
    }
}
declare namespace LocalJSX {
    interface AppBoard {
        "gamestate"?: Game;
        "onGrab"?: (event: CustomEvent<Move>) => void;
        "onMove"?: (event: CustomEvent<Move>) => void;
    }
    interface AppGameLocal {
    }
    interface AppGameOnline {
        "name"?: string;
    }
    interface AppHome {
    }
    interface AppPiece {
    }
    interface AppResults {
        "winner"?: number;
    }
    interface AppRoot {
    }
    interface IntrinsicElements {
        "app-board": AppBoard;
        "app-game-local": AppGameLocal;
        "app-game-online": AppGameOnline;
        "app-home": AppHome;
        "app-piece": AppPiece;
        "app-results": AppResults;
        "app-root": AppRoot;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-board": LocalJSX.AppBoard & JSXBase.HTMLAttributes<HTMLAppBoardElement>;
            "app-game-local": LocalJSX.AppGameLocal & JSXBase.HTMLAttributes<HTMLAppGameLocalElement>;
            "app-game-online": LocalJSX.AppGameOnline & JSXBase.HTMLAttributes<HTMLAppGameOnlineElement>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-piece": LocalJSX.AppPiece & JSXBase.HTMLAttributes<HTMLAppPieceElement>;
            "app-results": LocalJSX.AppResults & JSXBase.HTMLAttributes<HTMLAppResultsElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
        }
    }
}
