    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:GetObjectAcl
        - s3:PutObject
        - s3:PutObjectAcl
      Resource: 'arn:aws:s3:::${self:custom.buckets.clientBucket}/*'